# Uncomment the next line to define a global platform for your project
plugin 'cocoapods-binary'

platform :ios, '13.0'
use_frameworks!
#enable_bitcode_for_prebuilt_frameworks!
#keep_source_code_for_prebuilt_frameworks!
#all_binary!

target 'Poppin' do

  # Pods for Poppin
  pod 'Firebase/Auth'
  pod 'Firebase/Database', :binary => false
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage', '~> 8.0'
  pod 'Kronos'
  pod 'SFSafeSymbols', '~> 1.2.0'
  pod 'GeoFire', '~> 4.0'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Geofirestore', :git => 'https://github.com/imperiumlabs/GeoFirestore-iOS.git'
  pod 'SwiftDate', '~> 5.0'

  target 'PoppinTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PoppinUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
end
